# Generated by Django 4.2.2 on 2023-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
