# Generated by Django 4.2.2 on 2023-06-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_post_price_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
