# Generated by Django 4.2.2 on 2023-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(max_length=255)),
                ('client_email', models.CharField(max_length=255)),
                ('client_password', models.CharField(max_length=255)),
            ],
        ),
    ]
