# Generated by Django 4.2.2 on 2023-07-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_employee_signups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_signup',
            name='client_email',
            field=models.EmailField(max_length=255),
        ),
    ]
