# Generated by Django 4.1.4 on 2023-07-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_rename_employee_email_employee_signups_employee_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_email', models.EmailField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
            ],
        ),
    ]
