# Generated by Django 4.1.4 on 2023-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_admin_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
